import { evaluateCalculator, validateInputs } from "../calculator/index.js";
import type { CalculatorInputs, CompoundingFrequency, ContributionFrequency, ContributionTiming, CurrencyCode, EvaluationResult, ValidationIssue } from "../calculator/types.js";
export interface Drafts { currency:string; initialPrincipal:string; contributionAmount:string; contributionFrequency:string; contributionTiming:string; durationMonths:string; nominalAnnualRate:string; compoundingFrequency:string; nominalAnnualFeeRate:string; inflationRate:string; }
type Parsed<T>={ok:true;value:T}|{ok:false;issue:ValidationIssue};
const error=(field:keyof CalculatorInputs,code:ValidationIssue["code"],message:string):ValidationIssue=>({field,code,severity:"error",message});
const numeric=(raw:string,field:keyof CalculatorInputs,percent=false):Parsed<number>=>{if(!/^-?\d+(?:\.\d+)?$/.test(raw))return{ok:false,issue:error(field,"NOT_FINITE","Enter a finite amount/percentage")};const decimals=raw.split(".")[1]?.length??0;if(decimals>2)return{ok:false,issue:error(field,"TOO_MANY_DECIMALS","Use no more than 2 decimal places.")};if(field==="durationMonths"&&decimals)return{ok:false,issue:error(field,"INTEGER_REQUIRED","Enter a whole number of months.")};const value=Number(raw)/(percent?100:1);return Number.isFinite(value)?{ok:true,value}:{ok:false,issue:error(field,"NOT_FINITE","Enter a finite amount/percentage")}};
const enumValue=<T extends string>(raw:string,values:readonly T[],field:keyof CalculatorInputs):Parsed<T>=>{for(const value of values)if(raw===value)return{ok:true,value};return{ok:false,issue:error(field,"UNSUPPORTED_ENUM",`Choose a supported ${field}.`)}};
export const defaultDrafts=():Drafts=>({currency:"USD",initialPrincipal:"10000.00",contributionAmount:"500.00",contributionFrequency:"monthly",contributionTiming:"end",durationMonths:"120",nominalAnnualRate:"7.00",compoundingFrequency:"monthly",nominalAnnualFeeRate:"0.00",inflationRate:"3.00"});
export function draftsToInputs(d:Drafts):{inputs?:CalculatorInputs;errors:ValidationIssue[]}{const p=numeric(d.initialPrincipal,"initialPrincipal"),c=numeric(d.contributionAmount,"contributionAmount"),m=numeric(d.durationMonths,"durationMonths"),r=numeric(d.nominalAnnualRate,"nominalAnnualRate",true),f=numeric(d.nominalAnnualFeeRate,"nominalAnnualFeeRate",true),i=numeric(d.inflationRate,"inflationRate",true),cur=enumValue<CurrencyCode>(d.currency,["USD","EUR","GBP","CAD","AUD"],"currency"),cf=enumValue<ContributionFrequency>(d.contributionFrequency,["monthly","quarterly","annually"],"contributionFrequency"),ct=enumValue<ContributionTiming>(d.contributionTiming,["beginning","end"],"contributionTiming"),cmp=enumValue<CompoundingFrequency>(d.compoundingFrequency,["daily","monthly","quarterly","semi-annually","annually"],"compoundingFrequency");const all=[p,c,m,r,f,i,cur,cf,ct,cmp];const errors=all.flatMap(x=>x.ok?[]:[x.issue]);if(!p.ok||!c.ok||!m.ok||!r.ok||!f.ok||!i.ok||!cur.ok||!cf.ok||!ct.ok||!cmp.ok)return{errors};const inputs:CalculatorInputs={currency:cur.value,initialPrincipal:p.value,contributionAmount:c.value,contributionFrequency:cf.value,contributionTiming:ct.value,durationMonths:m.value,nominalAnnualRate:r.value,compoundingFrequency:cmp.value,nominalAnnualFeeRate:f.value,inflationRate:i.value};const checked=validateInputs(inputs);return{inputs:checked.inputs,errors:checked.errors}}
export function evaluateDrafts(d:Drafts):{evaluation?:EvaluationResult;errors:ValidationIssue[];inputs?:CalculatorInputs}{const parsed=draftsToInputs(d);return parsed.inputs&&parsed.errors.length===0?{inputs:parsed.inputs,evaluation:evaluateCalculator(parsed.inputs),errors:[]}:{errors:parsed.errors}}
