import { ContentPage, ContentSection } from "../../components/content-page";
import { createPageMetadata } from "../../lib/seo/publication";

export const metadata = createPageMetadata("/editorial-policy");

export default function EditorialPolicyPage() {
  return <ContentPage eyebrow="Publishing standards" title="Editorial policy" intro="This policy describes the evidence, attribution, review, correction, and update standards intended for this pre-launch financial tools project.">
    <ContentSection title="Current status"><p>The content is not formally published. Author and reviewer identities, operator responsibility, legal policies, production domain, and publication approval remain unconfirmed. The working product name is not an author or reviewer.</p></ContentSection>
    <ContentSection title="Evidence and calculation claims"><p>Financial explanations should distinguish common textbook formulas from the calculator’s exact implementation. Worked examples and comparisons must be generated by the same calculation engine as the live tool and checked against authoritative source material.</p></ContentSection>
    <ContentSection title="Authorship and review"><p>Author, reviewer, reviewed, and fact-checked labels may appear only when the responsible identities, dates, status, and supporting evidence are recorded. Missing facts remain visibly unassigned rather than inferred.</p></ContentSection>
    <ContentSection title="Updates and corrections"><p>Material changes should update the recorded date and receive proportionate review. A verified feedback channel will later support reports about calculations, content, accessibility, and other issues; no public channel is currently approved.</p></ContentSection>
    <ContentSection title="Independence and scope"><p>Educational content does not provide personalized financial, tax, investment, accounting, or legal advice. Jurisdiction-specific examples must state their scope and must not imply that a currency, language, number format, or IP-derived region determines a person’s legal position.</p></ContentSection>
  </ContentPage>;
}
