import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { CONTRIBUTION_EXAMPLE_INPUTS, CONTRIBUTION_EXAMPLE_RESULT, WORKED_EXAMPLE_INPUTS, WORKED_EXAMPLE_RESULT } from "../../lib/content/compound-interest.js";
import { calculate } from "../../lib/calculator/engine.js";
import { COMPOUND_INTEREST_EDITORIAL, getPublicEditorialState } from "../../lib/editorial/model.js";
import { FEEDBACK_CATEGORIES, buildFeedbackHref } from "../../lib/feedback.js";
import { SITE } from "../../lib/site.js";
import { COMPOUND_INTEREST_PAGE, STATIC_PUBLIC_PAGES, buildCanonical, buildSitemapEntries, createPageMetadata, getPublicationReadiness, getPublicRoutePathnames, getRobotsMetadata, type PublicationConfig } from "../../lib/seo/publication.js";
import { buildCompoundInterestSchema, serializeJsonLd } from "../../lib/seo/schema.js";

const ready: PublicationConfig = {
  approvedPublicName: "Approved Tools",
  legalOperator: "Example Operator Ltd",
  canonicalOrigin: "https://example.com",
  publicationStatus: "ready-for-publication",
  policyApprovals: { privacy: true, terms: true, disclaimer: true },
};

describe("publication and SEO safety", () => {
  it("defaults to prelaunch noindex and cannot index with incomplete approvals", () => {
    expect(SITE.publicationStatus).toBe("prelaunch");
    expect(getPublicationReadiness()).toMatchObject({ ready: false });
    expect(getRobotsMetadata()).toEqual({ index: false, follow: false });
    expect(getRobotsMetadata({ ...ready, legalOperator: null })).toEqual({ index: false, follow: false });
    expect(getRobotsMetadata(ready)).toEqual({ index: true, follow: true });
  });

  it("builds canonicals only from an approved HTTPS origin and normalized path", () => {
    expect(buildCanonical("/calculators/compound-interest?amount=1000#result", ready)).toBe("https://example.com/calculators/compound-interest");
    expect(buildCanonical("https://attacker.example/path", ready)).toBeNull();
    expect(buildCanonical("/path", { ...ready, canonicalOrigin: "http://example.com" })).toBeNull();
    expect(buildCanonical("/path", { ...ready, canonicalOrigin: "https://example.com/base" })).toBeNull();
    expect(buildCanonical("/path")).toBeNull();
  });

  it("keeps every public page title, description, and H1 unique", () => {
    const pages = [...STATIC_PUBLIC_PAGES, COMPOUND_INTEREST_PAGE];
    for (const key of ["title", "description", "h1"] as const) expect(new Set(pages.map((page) => page[key])).size).toBe(pages.length);
    expect(createPageMetadata("/contact").alternates).toBeUndefined();
  });

  it("builds a sitemap only from real static routes and live catalog routes", () => {
    expect(buildSitemapEntries()).toEqual([]);
    const paths = getPublicRoutePathnames();
    expect(paths).toContain("/calculators/compound-interest");
    expect(paths).toContain("/calculators/savings-goal");
    expect(paths.every((path) => !path.includes("?") && !/^\/(de|fr|es)(\/|$)/.test(path))).toBe(true);
    expect(buildSitemapEntries(ready).map(({ url }) => url)).toEqual(paths.map((path) => new URL(path, "https://example.com").toString()));
  });

  it("suppresses unsupported schema until facts are approved and serializes script-safe JSON", () => {
    expect(buildCompoundInterestSchema()).toEqual([]);
    const schema = buildCompoundInterestSchema(ready);
    expect(schema.map((item) => item["@type"])).toEqual(["WebApplication", "BreadcrumbList"]);
    expect(JSON.stringify(schema)).not.toMatch(/"@type":"(?:Organization|Person|FAQPage|Review|FactCheck)"|"(?:aggregateRating|ratingValue)"/i);
    expect(serializeJsonLd({ value: "</script><script>alert(1)</script>" })).not.toContain("<");
  });
});

describe("trust content contracts", () => {
  it("keeps both published examples generated by the frozen engine", () => {
    expect(WORKED_EXAMPLE_RESULT).toEqual(calculate(WORKED_EXAMPLE_INPUTS));
    expect(CONTRIBUTION_EXAMPLE_RESULT).toEqual(calculate(CONTRIBUTION_EXAMPLE_INPUTS));
    expect(WORKED_EXAMPLE_RESULT.finalBalance).toBeCloseTo(1102.5, 10);
    expect(CONTRIBUTION_EXAMPLE_RESULT.totalContributions).toBe(2400);
  });

  it("publishes exact formulas, event order, useful FAQ, and reference destinations", () => {
    const source = readFileSync(new URL("../../app/compound-interest-page.tsx", import.meta.url), "utf8");
    const styles = readFileSync(new URL("../../app/globals.css", import.meta.url), "utf8");
    expect(source).toContain("A = P(1 + r/n)");
    expect(source).toContain("(1 + <var>r</var>/<var>n</var>)");
    for (const phrase of ["beginning-of-period contribution", "equivalent monthly return", "annual fee", "end-of-period contribution", "closing balance"]) expect(source).toContain(phrase);
    expect(source).toContain("COMPOUND_INTEREST_FAQS.map");
    expect(source).toContain("Investor.gov");
    expect(source).toContain("Consumer Financial Protection Bureau");
    expect(source).not.toContain("FAQPage");
    expect(styles).toContain('.content-section[aria-labelledby="exact-model-heading"]');
    expect(styles).toContain('.content-section[aria-labelledby="limitations-heading"]');
    expect(styles).toContain(".editorial-status { display: block !important");
  });

  it("does not escalate missing editorial facts", () => {
    expect(getPublicEditorialState(COMPOUND_INTEREST_EDITORIAL)).toEqual({ updated: "2026-08-25", author: "Unassigned", reviewer: "No formal review recorded", factCheck: "Not claimed" });
    expect(getPublicEditorialState({ ...COMPOUND_INTEREST_EDITORIAL, reviewStatus: "reviewed" }).reviewer).toBe("No formal review recorded");
  });

  it("defines four feedback categories without exposing a form or mailto while unverified", () => {
    expect(FEEDBACK_CATEGORIES).toHaveLength(4);
    for (const category of FEEDBACK_CATEGORIES) expect(buildFeedbackHref(category.id, "/calculators/compound-interest")).toBeNull();
    const source = readFileSync(new URL("../../components/feedback-options.tsx", import.meta.url), "utf8");
    expect(source).not.toContain("<form");
  });
});
